version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      - name: "dependencies"
        dependencies:
          - package-ecosystem: "npm"
            directory: "/"
            package-file: "package.json"
            update-types: [ "version" ]
          - package-ecosystem: "npm"
            directory: "/"
            package-file: "package-lock.json"